[project]
name = "netball-stat-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.0.0",
    "streamlit>=1.43.1",
    "watchdog>=6.0.0",
]
